# Generated by Django 4.2.4 on 2023-08-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="condition",
            new_name="inner_tag",
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="answer",
            field=models.JSONField(default=dict),
        ),
    ]
