# Generated by Django 4.2.4 on 2023-08-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0003_alter_question_type_alter_questiondeckhint_hint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("text_array", "Text Array"),
                    ("scroll", "Scroll"),
                    ("multiple_scroll", "Multiple Scroll"),
                    ("select", "Select"),
                    ("link", "Link"),
                    ("time", "Time"),
                    ("photo", "Photo"),
                    ("multiple_links", "Multiple Links"),
                ],
                max_length=15,
            ),
        ),
    ]
