# Generated by Django 4.2.4 on 2023-08-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0005_alter_pitchdeck_name_alter_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("text_array", "Text Array"),
                    ("range", "Range"),
                    ("multiple_range", "Multiple Range"),
                    ("select", "Select"),
                    ("link", "Link"),
                    ("date", "Date"),
                    ("photo", "Photo"),
                    ("photo_description", "Photo Description"),
                    ("multiple_photo_description", "Multiple Photo Description"),
                    ("multiple_links", "Multiple Links"),
                ],
                max_length=26,
            ),
        ),
    ]
