# Generated by Django 4.2.4 on 2023-08-26 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0006_alter_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("text_array", "text array"),
                    ("range", "Range"),
                    ("multiple_range", "multiple range"),
                    ("select", "Select"),
                    ("link", "Link"),
                    ("date", "Date"),
                    ("photo", "Photo"),
                    ("multiple_photo", "multiple photo"),
                    ("photo_description", "photo description"),
                    ("multiple_link_description", "multiple link description"),
                    ("multiple_photo_description", "multiple photo description"),
                    ("multiple_links", "multiple links"),
                ],
                max_length=26,
            ),
        ),
        migrations.AlterField(
            model_name="questionanswer",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="decks.pitchdeck"
            ),
        ),
    ]
