# Generated by Django 4.2.4 on 2023-08-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0007_alter_question_type_alter_questionanswer_deck"),
    ]

    operations = [
        migrations.CreateModel(
            name="PdfToPPTXStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf", models.FileField(upload_to="pdf/")),
                ("pptx", models.FileField(blank=True, null=True, upload_to="pptx/")),
            ],
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("text_array", "text array"),
                    ("range", "Range"),
                    ("multiple_range", "multiple range"),
                    ("select", "Select"),
                    ("link", "Link"),
                    ("date", "Date"),
                    ("multiple_date_description", "multiple date description"),
                    ("photo", "Photo"),
                    ("multiple_photo", "multiple photo"),
                    ("photo_description", "photo description"),
                    ("multiple_link_description", "multiple link description"),
                    ("multiple_photo_description", "multiple photo description"),
                    ("multiple_links", "multiple links"),
                ],
                max_length=26,
            ),
        ),
    ]
