# Generated by Django 4.2.4 on 2023-08-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0008_pdftopptxstorage_alter_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitchdeck",
            name="images",
            field=models.JSONField(null=True),
        ),
    ]
